#!/bin/bash
#Ce fichier permet de compiler un projet Latex
#La première phase permet de préparer le répertoire de compilation
output_dir="Output"

#Vérification du dossier $output_dir
if [[ ! -d $output_dir ]]; then
	mkdir $output_dir
fi

#Vérification de l'argument 1
if [[ $1 = "" ]]; then
	echo ">>> Veuillez préciser le nom du fichier principal à générer..."
	echo ">>> Arret prématuré"
	exit
fi


echo -e "[Etape 1 / 7] >>> Nettoyage du répertoire $output_dir..."
rm -R $output_dir/*
echo -e "[Etape 1 / 7] >>> Nettoyage du répertoire $output_dir effectué"
echo -e "[Etape 2 / 7] >>> Nettoyage du fichier des journaux Latex..."
echo "" > render_report.txt
echo -e "[Etape 2 / 7] >>> Nettoyage du fichier des journaux Latex effectué"
echo -e "[Etape 3 / 7] >>> Première compilation du fichier $1.tex..."
pdflatex --output-dir=$output_dir $1 >> render_report.txt
echo -e "[Etape 3 / 7] >>> Première compilation du fichier $1.tex effectuée"
echo -e "[Etape 4 / 7] >>> Compilation du glossaire..."
makeglossaries $output_dir/$1 >> render_report.txt
echo -e "[Etape 4 / 7] >>> Compilation du glossaire effectuée"
echo -e "[Etape 5 / 7] >>> Compilation de la nomenclature...."
makeindex $output_dir/$1 >> render_report.txt
makeindex $output_dir/$1.nlo -s nomencl.ist -o $output_dir/$1.nls >> render_report.txt
echo -e "[Etape 5 / 7] >>> Compilation de la nomenclature effectuée"
echo -e "[Etape 6 / 7] >>> Seconde compilation du fichier $1.tex..."
pdflatex --output-dir=$output_dir $1 >> render_report.txt
echo -e "[Etape 6 / 7] >>> Seconde compilation du fichier $1.tex terminée"
echo -e "[Etape 7 / 7] >>> Déplacement du fichier $1.pdf..."
mv $output_dir/$1.pdf $1.pdf >> render_report.txt
echo -e "[Etape 7 / 7] >>> Déplacement du fichier $1.pdf à la racine du projet..."
echo -e ">>> Compilation terminée !"
