#!/bin/bash
part_dir="Parts"
echo -e "Vérification orthographique du répertoire $part_dir..."
for item in $part_dir/*
do

    if [ -d $item ]
    then
	echo -e ">>> Dossier $item en cours d'analyse !"

    for item_s in $item/*
    do
        echo -e "Voulez-vous analyser le fichier $item_s ? (y/n)"
        read reponse

        if [ "$reponse" = "y" ];
        then
            aspell --encoding=utf-8 --lang=fr_FR.UFT-8 -c "$item_s" 
        fi
    done
    fi
done
echo -e ">>> Vérification orthographique terminée !"
